version: '3.8'
services:
  redis.admin:
    container_name: redis.admin
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    networks:
      - network-admin
  postgres.admin:
    container_name: postgres.admin
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_SUPER_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_SUPER_USERNAME:-postgres}
      - POSTGRES_DB=${DB_SUPER_DATABASE:-postgres}
    networks:
      - network-admin
  admin.fpm:
    container_name: admin.fpm
    build:
      context: .
      target: fpm
    image: devoptimus/admin-fpm
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}

      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY="base64:CyUNByT3Wh2gIoRoibP52U1E7jKf1ef5MwHq29h2H9E="

      - DB_SUPER_DATABASE=${DB_SUPER_DATABASE:-postgres}
      - DB_SUPER_USERNAME=${DB_SUPER_USERNAME:-postgres}
      - DB_SUPER_PASSWORD=${DB_SUPER_PASSWORD:-postgres}

      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-postgres.admin}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-db_admin}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - REDIS_HOST=${REDIS_HOST:-redis.admin}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - SESSION_DRIVER=${SESSION_DRIVER:-redis}
    volumes:
      - .:/home/app/public_html
    depends_on:
      - redis.admin
      - postgres.admin
    networks:
      - network-admin
  admin.nginx:
    container_name: admin.nginx
    build:
      context: .
      target: nginx
    image: devoptimus/admin-nginx
    ports:
      - ${APP_PORT:-0}:80
    environment:
      - FPM_HOST="admin.fpm:9000"
    depends_on:
      - admin.fpm
    volumes:
      - ./public:/home/app/public_html/public
    networks:
      - network-admin
  admin.node:
    container_name: admin.node
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    image: devoptimus/admin-node
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/public_html
      - ./node_modules:/home/app/public_html/node_modules
    command: ['npm', 'run', 'dev']
    networks:
      - network-admin
networks:
  network-admin:
    name: network-admin
    driver: bridge
