version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:alpine
    networks:
     - app-lan
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-lan
  admin.fpm:
    container_name: admin.fpm
    image: devoptimus/admin-fpm
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      
      - DB_CONNECTION_ROOT:${DB_CONNECTION_ROOT-pgsql}
      - DB_HOST_ROOT:${DB_HOST_ROOT:-postgres}
      - DB_PORT_ROOT:${DB_PORT_ROOT:-5432}
      - DB_DATABASE_ROOT:${DB_DATABASE_ROOT:-postgres}
      - DB_USERNAME_ROOT:${DB_USERNAME_ROOT:-postgres}
      - DB_PASSWORD_ROOT:${DB_PASSWORD_ROOT:-postgres}

      - DB_CONNECTION:${DB_CONNECTION:-pgsql}
      - DB_HOST:${DB_HOST:-postgres}
      - DB_PORT:${DB_PORT:-5432}
      - DB_DATABASE:${DB_DATABASE:-db_admin}
      - DB_USERNAME:${DB_USERNAME:-admin}
      - DB_PASSWORD:${DB_PASSWORD:-admin}
    volumes:
      - .:/home/app/public_html
    networks:
      - app-lan
  admin.nginx:
    container_name: admin.nginx
    image: devoptimus/admin-nginx
    ports:
      - ${APP_PORT:-0}:80
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - FPM_HOST="admin.fpm:9000"
    depends_on:
      - admin.fpm
    volumes:
      - ./public:/home/app/public_html/public
    networks:
      - app-lan
  admin.node:
    container_name: admin.node
    image: devoptimus/admin-node
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/public_html
      - ./node_modules:/home/app/public_html/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - app-lan
networks:
  app-lan:
    
  