version: '3.8'
services:
  admin:
    container_name: admin-http
    build: nginx-http
    volumes:
      - .:/home/www
    environment:
      - POOL_UID=${PHP_FPM_POOL_UID:-1000}
      - POOL_GID=${PHP_FPM_POOL_GID:-1000}
    ports:
      - 8000:80
