apiVersion: v1
kind: Secret
metadata:
  name: ged-admin-secret
type: Opaque
data:
  APP_KEY: YmFzZTY0OkNqUjJWbjRVK0dUeXcrUEpLRTRhckNubWhGWk0xVldmbndHNTZ4cytSQk09Cg==

  SYSTEM_PASSWORD: c3lzdGVt
  ADMIN_PASSWORD: YWRtaW4=

  DB_USERNAME: b3B0aW11cw==
  DB_PASSWORD: cGFzc3dvcmQ=

  DB_SUPER_DATABASE: cG9zdGdyZXM=
  DB_SUPER_USERNAME: cG9zdGdyZXM=
  DB_SUPER_PASSWORD: cG9zdGdyZXM=

  REDIS_PASSWORD: bnVsbA==
  
  AWS_ACCESS_KEY_ID: bnVsbA==
  AWS_SECRET_ACCESS_KEY: bnVsbA==
