apiVersion: v1
kind: Service
metadata:
  name: ged-admin-nginx
spec:
  type: LoadBalancer
  selector:
    app: ged-admin-nginx
  ports:
    - port: 80
      targetPort: 80
# Metallb
# Install
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
# kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s
