apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  REPLICANT_USERNAME: cmVwbGljYW50
  REPLICANT_PASSWORD: cmVwbGljYW50
