apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-grpc-server
spec:
  selector:
    matchLabels:
      app: client-grpc-server
  template:
    metadata:
      labels:
        app: client-grpc-server
    spec:
      containers:
        - name: client-grpc-server
          image: devoptimus/ged-client-grpc-server
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: "client-config"
            - secretRef:
                name: "client-secret"
          volumeMounts:
            - name: storage
              mountPath: /home/app/public_html/storage/app
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-pvc
