apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: client
  accessModes:
    - ReadWriteOnce
