apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/images
    server: 192.168.0.162