apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: admin
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/k8s
    server: 192.168.0.162
