apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-pvc
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  storageClassName: admin
  accessModes:
    - ReadWriteOnce
