apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  REPLICANT_USERNAME: cmVwbGljYW50
  REPLICANT_PASSWORD: cmVwbGljYW50
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-writer
spec:
  selector:
    matchLabels:
      app: postgres-writer
  serviceName: postgres-writer
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-writer
    spec:
      containers:
        - name: postgres-writer
          image: devoptimus/postgres:latest
          ports:
            - containerPort: 5432
              name: postgres-writer
          readinessProbe:
            tcpSocket:
              port: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/writer
          envFrom:
            - secretRef:
                name: "postgres-secret"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-writer
spec:
  selector:
    app: postgres-writer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-reader
spec:
  selector:
    matchLabels:
      app: postgres-reader
  serviceName: postgres-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-reader
    spec:
      containers:
        - name: postgres-reader
          image: devoptimus/postgres:latest
          ports:
            - containerPort: 5432
              name: postgres-reader
          env:
              - name: PGDATA
                value: /var/lib/postgresql/reader
              - name: MASTER_SERVER
                value: postgres-writer
              - name: MASTER_PORT
                value: "5432"
              - name: SLOT_NAME
                value: master
          readinessProbe:
            tcpSocket:
              port: 5432
          envFrom:
            - secretRef:
                name: "postgres-secret"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reader
spec:
  selector:
    app: postgres-reader
  ports:
    - port: 5432
      targetPort: 5432