apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/data
    server: host.ip # ex: 192.168.0.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: data
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/images
    server: host.ip # ex: 192.168.0.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: client
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: admin
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/k8s
    server: host.ip # ex: 192.168.0.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-pvc
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  storageClassName: admin
  accessModes:
    - ReadWriteOnce